
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NUM OPFrase : ElementosElementos : Elementos OP ElementosElementos : ElementoElemento : NUM'
    
_lr_action_items = {'NUM':([0,5,],[4,4,]),'$end':([1,2,3,4,6,],[0,-1,-3,-4,-2,]),'OP':([2,3,4,6,],[5,-3,-4,5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Frase':([0,],[1,]),'Elementos':([0,5,],[2,6,]),'Elemento':([0,5,],[3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Frase","S'",1,None,None,None),
  ('Frase -> Elementos','Frase',1,'p_Frase','pratica_yacc.py',27),
  ('Elementos -> Elementos OP Elementos','Elementos',3,'p_Elementos','pratica_yacc.py',30),
  ('Elementos -> Elemento','Elementos',1,'p_Elementos_simples','pratica_yacc.py',38),
  ('Elemento -> NUM','Elemento',1,'p_Elemento','pratica_yacc.py',42),
]
